### PR TITLE
ci: cache libgit2 install

### PR DESCRIPTION
**Pull request by antoineco**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [x] Updated relevant documentation.

### Description of changes

Cache `install` directory for libgit2 static build to speed up CI retries.

### CODE REVIEW

**Comment by antoineco** [comment]
It doesn't seem to be making any difference in the build time of libgit2/git2go after a re-try.

I suspect that there is another cache involved though. One my machine, the (re-)build is almost instant if I delete `third_party/libgit2/git2go/static-build/install`.

Or maybe it has to do with the files' timestamps.

**Comment by antoineco** [comment]
The cache doesn't help. Make is forcing a rebuild.

attempt 1
image

attempt 2
image

**Comment by antoineco** [comment]
The trick was simply to reset the mtime of `lib/pkgconfig/libgit2.pc` on a cache hit:

image

**Review by nderjung — APPROVED** [review]
The numbers speak for themselves. Awesome, thanks!

Approved-by: Alexander Jung <alex@unikraft.io>

**Pull request merged**
