### PR TITLE
fix(initrd): corrupted symlinks

### PR DESCRIPTION
**Pull request by antoineco**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

Due to an issue upstream (https://github.com/cavaliergopher/cpio/issues/15) files with mode Symlink are written as zero-sized files, without symlink target:

Output of Unikraft:
```
Info: [libukcpio] <cpio.c @  298> Creating symlink /bin/arch
Info: [libukcpio] <cpio.c @  316> /bin/arch: Target is
dbg:  [libvfscore] <main.c @ 1668> (int) uk_syscall_r_symlink((const char*) 0x11eb0, (const char*) 0x43d2e0020)
ERR:  [libukcpio] <cpio.c @  318> /bin/arch: Failed to create symlink: Unknown error 0 (0)
```

Output of included tests:
```
=== RUN   TestNewFromMapping
    initrd_test.go:82: file [./lib/libtest.so.1]: got mode 0100000, expected 0120000
    initrd_test.go:85: file [./lib/libtest.so.1]: got linkname "", expected "libtest.so.1.0.0"
    initrd_test.go:88: file [./lib/libtest.so.1]: got size 16, expected 0
```

This PR refactors the `NewFromMapping` function to use a (hopefully temporary) fork which includes the relevant fix (https://github.com/cavaliergopher/cpio/issues/16).

Additionally, I refactored the logic a little for readability.

### CODE REVIEW

**Comment by craciunoiuc** [comment]
Code looks good, will try on Monday 🙏

**Comment by antoineco** [comment]
I just learned @nderjung was already working on this.

**Comment by craciunoiuc** [comment]
it worked btw

**Comment by antoineco** [comment]
I know, I included tests.

**Pull request closed without merging**
