### PR TITLE
feat(compose): Introduce `--remove-orphans` flag

### PR DESCRIPTION
**Pull request by LucaSeri**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [x] Updated relevant documentation.

### Description of changes

The `remove-orphans` flag remove all machines that are no longer part of the composefile, but that were previously part of the project.

### CODE REVIEW

**Comment by nderjung** [comment]
Hi @LucaSeri, looks good overall. I just checked the normal `docker compose` subcommands and it looks like the flag works the opposite way, i.e. `--orphans`. Any reason why the flag was inverted?

(Also PR now requires a rebase)

**Comment by LucaSeri** [comment]
Hi @nderjung, thanks! I rebased the PR. Can you tell me which subcommand you are referring to? I was not able to find the flag:
```
$ docker compose create --help

Usage:  docker compose create [OPTIONS] [SERVICE...]

Creates containers for a service.

Options:
      --build            Build images before starting containers.
      --dry-run          Execute command in dry run mode
      --force-recreate   Recreate containers even if their configuration and image haven't changed.
      --no-build         Don't build an image, even if it's policy.
      --no-recreate      If containers already exist, don't recreate them. Incompatible with --force-recreate.
      --pull string      Pull image before running ("always"|"missing"|"never"|"build") (default "policy")
      --remove-orphans   Remove containers for services not defined in the Compose file.
      --scale scale      Scale SERVICE to NUM instances. Overrides the scale setting in the Compose file if present.
```

**Comment by nderjung** [comment]
Ah, apologies, it looks totally mixed between the two:

| Command | `--orphans` | `--remove-orphans` | TODO |
|-|-|-|-|
| `docker compose build` | ❌ | ❌ | Remove from PR. |
| `docker compose create` | ❌ | ✅ | N/a |
| `docker compose down` | ❌ | ✅ | N/A |
| `docker compose logs` | ❌ | ❌ | Remove from PR. |
| `docker compose pause` | ❌ | ❌ | Remove from PR. |
| `docker compose ps` | ✅ | ❌ | Invert flag. |
| `docker compose start` | ❌ | ❌ | Remove from PR. |
| `docker compose stop` | ❌ | ❌ | Remove from PR. |
| `docker compose unpause` | ❌ | ❌ | Remove from PR. |
| `docker compose up` | ❌ | ✅ | N/a. |

Since it's very intermittent, you can localize the flag to the individual subcommands.

**Comment by LucaSeri** [comment]
Thanks @nderjung for noticing this and writing it all up. I updated the PR according to the table.

**Review by nderjung — APPROVED** [review]
Amazing, thanks!

**Pull request merged**
