### PR TITLE
cmd/kraft: Error on no target arch/plat

### LINKED ISSUE #185: Error out on invalid platform
Given this `Kraftfile`:

```yaml
# Kraftfile
specification: v0.5

unikraft: stable

targets:
  - name: default
    architecture: x86_64
    platform: kvm
```

It would be great, if running `kraft build --plat linuxu` would return with a non-zero error code and provide an error message instead of silently not building anything.

### PR DESCRIPTION
**Pull request by craciunoiuc**
Signed-off-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

Closes: #185

### CODE REVIEW

**Comment by mkroening** [comment]
Does this make KraftKit return with a non-zero error code on the shell?

**Comment by craciunoiuc** [comment]
Yes :)

```
➜  helloworld ~/kraftkit/dist/kraft build -m x86_63 -p kvm .
[+] finding core/unikraft:staging...                                                           [0.0s]
[+] pulling core/unikraft:staging ####################################################### 100% [0.0s]
no targets selected to build
➜  helloworld echo $?
1
```

**Comment by mkroening** [comment]
Awesome 🥳

**Review by nderjung — APPROVED** [review]
Thanks!

**Pull request merged**
