### PR TITLE
feat: Upgrade to Go 1.20.6

### PR DESCRIPTION
**Pull request by nderjung**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

Updates the version of Go use across the project to 1.20.6.

### CODE REVIEW

**Review by antoineco — APPROVED** [review]

**Review by antoineco — DISMISSED** [review]
https://github.com/unikraft/kraftkit/blob/41715c56e02432149560a8dc2600b351125f6194/.github/workflows/gobuild-qemu-devices.yaml#L25

**Comment by antoineco** [comment]
We have a chicken and egg problem. The build env image needs to be updated and pushed for the builds to succeed:
https://github.com/unikraft/kraftkit/blob/cb0e6d4894e7c33224551d8f21587b06b933f270/.github/workflows/gobuild-qemu-devices.yaml#L41

**Comment by craciunoiuc** [comment]
we can just push manually :magic_wand: and then rebase

@nderjung let me know when I can build/push

**Comment by craciunoiuc** [comment]
`1.20.6` please :pray:

**Review by antoineco — APPROVED** [review]

**Pull request merged**
