### PR TITLE
Migrate errors to constants

### LINKED ISSUE #102: Migrate all errors to constants
This issue tracks migrating all thrown errors from the format:

```go
  ...
  if err != nil {
    return fmt.Errorf("an error occurred")
  }
  ...
```

To:

```go
var (
  ErrAnErrorOccurred = errors.New("an error occurred")
)

  ...
  if err != nil {
    return ErrAnErrorOccurred
  }
  ...
```

### PR DESCRIPTION
**Pull request by gabrielmocanu**
Migrate errors to constants

Closes: #102

### CODE REVIEW

**Comment by nderjung** [comment]
Hi @gabrielmocanu what's the status of this PR, are there more commits to be added?

**Comment by gabrielmocanu** [comment]
Hi @nderjung .

No, last time when I checked this was all. I was waiting for your review and I don't know if I should do something with the Codacy issue.

**Comment by nderjung** [comment]
Ok, above all errors, simply write:

```go
// Error definitions for common errors used in X.
var (
  ErrXXX
)
```

Where `X` is the (sub)package.

**Comment by gabrielmocanu** [comment]
@nderjung  Done!

**Pull request closed without merging**
