### PR TITLE
fix: Alias platform argument

### LINKED ISSUE #657: kraft build fails to correctly filter targets with "kvm" platform
### Describe the bug

Filtering using the -p flag and targetting "kvm" specifically, doesn't match targets from the kraft.yaml file.

Before filtering, "kvm" gets aliased to "qemu". As a result, the filtering matches no targets.

### Steps to reproduce

Given this sample kraft.yaml file:

```yaml
specification: '0.5'
name: helloworld
unikraft:
  version: stable
targets:
  - architecture: x86_64
    platform: kvm
  - architecture: arm64
    platform: xen
```

Run the command:

```sh
kraft build -p kvm
```

Build exits with the error:

```sh
no choices provided.
 ```

### Expected behavior

Command should select the target with platform "kvm".

### Which architectures were you using or does this bug affect?

_No response_

### Which operating system were you using or does this bug affect?

_No response_

### Relevant log output

```shell
no choices provided.
```

### PR DESCRIPTION
**Pull request by craciunoiuc**
### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR;
  - [ ] Updated relevant documentation.

### Description of changes

GitHub-Fixes: #657

### CODE REVIEW

**Comment by jake-ciolek** [comment]
Thanks. Would it be possible to define that code once and use it as a method or a function?

**Comment by craciunoiuc** [comment]
of course :magic_wand:

**Comment by craciunoiuc** [comment]
@jake-ciolek check again

Changed the logic a bit. Now it returns the same string if not found (it will fail anyways at a later step if wrong)

**Review by jake-ciolek — APPROVED** [review]
Thanks. I tried it out and when using "-p kvm", filtering works as expected.

**Pull request merged**
