### PR TITLE
fix(webinstall): Escape '[trusted=yes]' for kraftkit.list

### PR DESCRIPTION
**Pull request by akira-kurogane**
### Description of changes

Currently install.sh runs:

```sh
echo deb [trusted=yes] https://deb.pkg.kraftkit.sh / | tee /etc/apt/sources.list.d/kraftkit.list
```

which becomes the following if there is a file matching the glob pattern "[trusted=yes]"
```
deb <name of file in current directory> https://deb.pkg.kraftkit.sh /
```

This commit adds necessary escaping to prevent it.

### Prerequisite checklist

  - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
  - [x] Tested your changes against relevant architectures and platforms;
  - [x] Ran `make fmt` on your commit series before opening this PR; N/A
  - [x] Updated relevant documentation. N/A

### CODE REVIEW

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by craciunoiuc** [comment]
@akira-kurogane thanks for this

The fix looks good, can you rename the commit to: `fix(webinstall): Escape '[trusted=yes]' for kraftkit.list`

**Comment by akira-kurogane** [comment]
> @akira-kurogane thanks for this
> 
> The fix looks good, can you rename the commit to: `fix(webinstall): Escape '[trusted=yes]' for kraftkit.list`

I see this change has been made. And that's fine by me.

**Comment by akira-kurogane** [comment]
I don't know how to trigger the checks again - something an owner in this repo can do maybe?

**Comment by nderjung** [comment]
@akira-kurogane thanks for this contribution! To clarify, the commit message title requires changing in addition to the PR title.  Once reworded, force-pushing to your existing branch should re-trigger the check.

**Comment by akira-kurogane** [comment]
Thanks for that clarification nderjung, but I'm afraid I cannot do that (change the commit message). I used the github.com GUI rather than shell to write up the first commit, and I can't change the commit message using the GUI. Syncing and updating this same PR leads to an auto-assigned new commit title ("Merge branch 'unikraft:staging' into patch-1").

Let's just chuck it in the bin.

**Pull request closed without merging**
